Update with service health initiative
Azure/alz-monitor pull request #141
Opened 2023-04-28 14:21 UTC by jfaurskov

Modify workflows to deploy service health initiative and assign it
Create Service health inititative including service health alerts and alert processing policy
Modify existing initiatives to remove service health alert policies
Update existing assign bicep files to remove alert processing policy
Add assign bicep file for service health alert initiative
Modify existing parameter files to remove service health alerts
create parameter file for service health alert initiative
Update deployment guide

2023-05-02 00:10 UTC, arjenhuitema submitted a review, later dismissed
LGTM

2023-05-02 08:54 UTC, paulgrimley requested changes

2023-05-02 08:54 UTC, paulgrimley commented on docs/wiki/DeploymentGuide.md
> -> **NOTE:** If you are looking to align your Azure environment to Azure landing zone, please see [Transition existing Azure environments to the Azure landing zone conceptual architecture](http://aka.
@jfaurskov you need to put this back in as you have removed brownfield guidance i added

2023-05-02 08:54 UTC, paulgrimley commented on docs/wiki/DeploymentGuide.md
> -> **NOTE:** If you are looking to align your Azure environment to Azure landing zone, please see [Transition existing Azure environments to the Azure landing zone conceptual architecture](http://aka.
@jfaurskov i need to spend sometime with you reviewing this as you changed a lot in here with removal of commands and wanted to check

2023-05-03 11:50 UTC, paulgrimley approved these changes
Reviewed deployment guide offline and good with changes

2023-05-03 13:23 UTC, merged