deploy individual initiatives
Azure/alz-monitor pull request #179
Opened 2023-06-12 22:00 UTC by arjenhuitema

Added documentation to deploy individual initiatives.

2023-06-14 10:10 UTC, paulgrimley approved these changes
Approved

2023-06-14 11:15 UTC, paulgrimley requested changes
Requested some changes so we make sure Service Health is more prominent and also wanted some clarity on a couple of things

2023-06-14 11:15 UTC, paulgrimley commented on docs/wiki/Deploy-individual-Policy-Initiatives.md
> +- You can choose deploy all the Policy Definitions, this is recommended when other initiatives will be implemented in the future.
i'm a little confused reading this and not clear on what is trying to be said, perhaps an example could help.

2023-06-14 11:15 UTC, paulgrimley commented on docs/wiki/Deploy-individual-Policy-Initiatives.md
> +Using either a PowerShell prompt or Azure CLI, navigate to the root of the cloned repo and log on to Azure with an account with at least Resource Policy Contributor access at the root of the manageme
```suggestion
Using either a PowerShell prompt or Azure CLI, navigate to the root of the cloned repo and log on to Azure with an account with at least [Resource Policy Contributor](https://learn.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#resource-policy-contributor) access at the root of the management group hierarchy where you will be creating the policies and initiatives.
```

Wondering if we should add a link to this RBAC role - also wondering if this means we need to update other files where this has been copied from, can you check?

2023-06-14 11:15 UTC, paulgrimley commented on docs/wiki/Introduction-to-deploying-ALZ-Monitor.md
> +- To deploy an individual Policy Initiative, please proceed with [Deploy individual Policy Initiatives](./Deploy-individual-Policy-Initiatives)
```suggestion
-  To deploy Service Health or another Policy Initiative (individually), please proceed with [Deploy individual Policy Initiatives](./Deploy-individual-Policy-Initiatives)
```

2023-06-14 11:15 UTC, paulgrimley commented on docs/wiki/_Sidebar.md
> +   * [Deploy individual Policy Initiatives](./Deploy-individual-Policy-Initiatives)
```suggestion
   * [Deploy Service Health or individual Policy Initiatives](./Deploy-individual-Policy-Initiatives)
```

2023-06-14 11:59 UTC, arjenhuitema commented on docs/wiki/Deploy-individual-Policy-Initiatives.md
> +Using either a PowerShell prompt or Azure CLI, navigate to the root of the cloned repo and log on to Azure with an account with at least Resource Policy Contributor access at the root of the manageme
Yes, if we change this, we should make the same changes in the other deployment guides.

2023-06-15 08:28 UTC, jfaurskov commented on docs/wiki/Deploy-individual-Policy-Initiatives.md
> +Using either a PowerShell prompt or Azure CLI, navigate to the root of the cloned repo and log on to Azure with an account with at least Resource Policy Contributor access at the root of the manageme
I feel we are muddying the waters a bit here. In all of our other documentation we have specified either Az CLI or PowerShell, but here we are mixing the two somewhat. Shouldn't we do one Az CLI and one PowerShell, clearly separated?

2023-06-15 10:52 UTC, paulgrimley commented on docs/wiki/Deploy-individual-Policy-Initiatives.md
> +Using either a PowerShell prompt or Azure CLI, navigate to the root of the cloned repo and log on to Azure with an account with at least Resource Policy Contributor access at the root of the manageme
Are you able to update the other links as part of this PR Arjen please if it is not too much work

2023-06-15 13:35 UTC, arjenhuitema commented on docs/wiki/Deploy-individual-Policy-Initiatives.md
> +Using either a PowerShell prompt or Azure CLI, navigate to the root of the cloned repo and log on to Azure with an account with at least Resource Policy Contributor access at the root of the manageme
This comes directly from our Azure CLI deployment guide. And the point here is not whether you use the Azure PowerShell deployment method or the Azure CLI deployment method. It´s about the command line tool preference. I do agree that our documentation can be clearer on this point, maybe we should rephrase this as:

> Open your preferred command line tool _(Windows PowerShell, Cmd, Bash or other Unix shells), and navigate to the root of the cloned repo and log on to Azure with an account with at least Resource Policy Contributor access at the root of the management group hierarchy where you will be creating the policies and initiatives.

2023-06-15 14:08 UTC, arjenhuitema commented on docs/wiki/Deploy-individual-Policy-Initiatives.md
> +Using either a PowerShell prompt or Azure CLI, navigate to the root of the cloned repo and log on to Azure with an account with at least Resource Policy Contributor access at the root of the manageme
> Shouldn't we do one Az CLI and one PowerShell, clearly separated?

Sure, I can create a new page for a PowerShell specific deployment, I thought that it would be a bit redundant?

2023-06-19 12:23 UTC, paulgrimley submitted a review, later dismissed
Thanks @arjenhuitema LGTM, @jfaurskov can you take a look?

2023-06-20 08:20 UTC, jfaurskov commented on docs/wiki/Introduction-to-deploying-ALZ-Monitor.md
> +- To deploy Service Health or another Policy Initiative (individually), please proceed with [Deploy individual Policy Initiatives with Azure PowerShell](./Deploy-individual-Policy-Initiatives-with-Az
```suggestion
- To deploy Service Health or another Policy Initiative (individually) with PowerShell, please proceed with [Deploy individual Policy Initiatives with Azure PowerShell](./Deploy-individual-Policy-Initiatives-with-Azure-PowerShell)
```

2023-06-20 08:20 UTC, jfaurskov commented on docs/wiki/_Sidebar.md
> +   * [Deploy Service Health or individual Policy Initiatives with Azure CLI](./Deploy-individual-Policy-Initiatives-with-Azure-CLI)
```suggestion
   * [Deploy individual Policy Initiatives with Azure CLI](./Deploy-individual-Policy-Initiatives-with-Azure-CLI)
```

2023-06-20 08:21 UTC, jfaurskov commented on docs/wiki/_Sidebar.md
> +   * [Deploy Service Health or individual Policy Initiatives with Azure PowerShell](./Deploy-individual-Policy-Initiatives-with-Azure-PowerShell)
```suggestion
   * [Deploy individual Policy Initiatives with Azure PowerShell](./Deploy-individual-Policy-Initiatives-with-Azure-PowerShell)
```

2023-06-20 08:21 UTC, jfaurskov requested changes
Excellent work @arjenhuitema just a few suggestions. :-)

2023-06-20 13:16 UTC, arjenhuitema commented
@jfaurskov great suggestions. Committed all.

2023-06-20 14:05 UTC, jfaurskov approved these changes
LGTM

2023-06-20 14:05 UTC, merged