Add Azure Devops pipeline sample
Azure/alz-monitor pull request #183
Opened 2023-06-20 08:10 UTC by jfaurskov

## Description
Adds Azure Devops pipeline sample and related documentation. Replaces #166 

## Changes
- Remove erronous comment from sample Github Action workflow
- Add /azure-pipelines/sample-pipeline.yml
- Add /docs/wiki/Deploy-with-Azure-Pipelines.md
- Add link to /docs/wiki/Deploy-with-Azure-Pipelines.md in /docs/wiki/Customize-Policy-Assignment
- Add links to /docs/wiki/Deploy-with-Azure-Pipelines.md in /docs/wiki/Introduction-to-deploying-ALZ-Monitor
- Add link to /docs/wiki/Deploy-with-Azure-Pipelines.md in /docs/wiki/_Sidebar

## Testing evidence

![image](https://github.com/Azure/alz-monitor/assets/22591930/702565f4-0c1e-43ef-8a4d-b19f8d0f90ad)

2023-06-22 12:28 UTC, paulgrimley requested changes
I've reviewed the docs, need @Alboroni and / or @pkorolo to review and test pipeline

2023-06-22 12:28 UTC, paulgrimley commented on docs/wiki/Deploy-with-Azure-Pipelines.md
> +First configure your Azure DevOps project with a pipeline hosted in Github as described [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#access
```suggestion
First configure your Azure DevOps project with a pipeline hosted in GitHub as described [here](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#access-to-github-repositories). The pipeline should be configured to use the [sample-pipeline.yml](../../azure-pipelines/sample-pipeline.yml) file.
```

2023-06-22 12:28 UTC, paulgrimley commented on docs/wiki/Deploy-with-Azure-Pipelines.md
> +
Are we missing a Service Health parameter? if not can we add a note - we may also need to go back and change the GH action

2023-06-29 06:41 UTC, jfaurskov commented on docs/wiki/Deploy-with-Azure-Pipelines.md
> +
We are not. The service health initiative is assigned at the intermediate root management group level which is set in line 66. I see no reason to add any notes.

2023-06-29 09:44 UTC, paulgrimley submitted a review, later dismissed
LGTM

2023-06-29 09:45 UTC, paulgrimley reviewed
Approved pending technical review of pipeline

2023-07-10 08:20 UTC, Springstone approved these changes
Looks good to me. Reviewed the sample pipeline and it's pretty straightforward - running the same commands as in the deployment wiki.

2023-07-10 08:25 UTC, merged