Update script to enforce consistency and fix small errors during cleanup
Azure/alz-monitor pull request #240
Opened 2023-08-29 14:50 UTC by Brunoga-MS

@jfaurskov : Hello Jan, can you please validate and approve?

2023-08-31 14:46 UTC, arjenhuitema requested changes
Thank you Bruno, looks good!

Can you provide some evidence on running the cleanup script. What was the error that is solved with this? 

Please remove the changes to docs/wiki/Deploy-with-Azure-PowerShell.md the deployment location is intentional.

2023-08-31 14:46 UTC, arjenhuitema commented on docs/wiki/Deploy-with-Azure-PowerShell.md
>    #Deploy policy initiatives, wait approximately 1-2 minutes after deploying policies to ensure that there are no errors when creating initiatives
We intentionally deploy the PolicyDefinitions and the PolicySetDefinitions to the pseudo root management group. Only the assignments are made to the specific management groups.

2023-09-01 09:54 UTC, Brunoga-MS commented on docs/wiki/Deploy-with-Azure-PowerShell.md
>    #Deploy policy initiatives, wait approximately 1-2 minutes after deploying policies to ensure that there are no errors when creating initiatives
Hey @arjenhuitema,
changes to docs/wiki/Deploy-with-Azure-PowerShell.md the removed. This is the error you get with the force parameter on the Remove-AzRoleAssignment
![image](https://github.com/Azure/alz-monitor/assets/26008435/a267453d-9830-4103-b3d4-5bbfb9ece3ac)

2023-09-01 13:36 UTC, arjenhuitema approved these changes
LGTM

2023-09-01 13:37 UTC, merged